Repository ProxyKit/ProxyKit, pull requests merged in 2019-03, with the labels that each got.

#72 Fancy Recipe for Proxy with Client-Certificate
  src/Recipes/13_ClientCertificate.cs
  src/Recipes/badssl.com-client.p12
Labels: enhancement

#80 Fix Options Pattern, issue #74.
  src/ProxyKit/ServiceCollectionExtensions.cs
  src/ProxyKit/WebSocketProxyMiddleware.cs
Labels: bug

#88 Downgrade dependencies to 2.1.0 . Fixes #85
  src/ProxyKit/ProxyKit.csproj
Labels: dependencies
